# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#

title: ML and Data from the Norwegian countryside 
description: ML, Python and visualisation of data
github_username: chrcoello

# Email and twitter are optional:
#twitter_username: ChrCoello
linkedin_username: ChrCoello

# OPTIONAL: override baseurl and url if using a custom domain
#url:  the base hostname & protocol for your site, e.g. http://example.com
#baseurl: the subpath of your site, e.g. /blog

# Set this to true to get LaTeX math equation support
use_math: True

# Add your Google Analytics ID here if you have one and want to use it
google_analytics:

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
#remote_theme: pages-themes/midnight@v0.2.0

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jemoji

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
